apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: ansible-create-project-template
  title: Create Ansible Project
  description: Create a new Ansible Project
  tags:
    - recommended
    - ansible
    - project
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
    - title: Project data
      description: Provide project data
      required:
        - token
        - organization
        - scmUrl
      properties:
        token:
          title: Token
          type: string
          description: Oauth2 token
          ui:field: AAPTokenField
          ui:backstage:
            review:
              show: true
        scmType:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: Github
          enum:
            - Github
            - Gitlab
        organization:
          title: Organization
          type: string
          description: Select organization
          resource: organizations
          ui:field: AAPResourcePicker
          default:
            id: 1
            name: Default
        credentials:
          title: Credentials
          type: string
          description: Select SCM credential for Private repositories
          resource: credentials
          ui:field: AAPResourcePicker
        scmUrl:
          title: Source control URL
          type: string
          ui:help: 'Source control URL: gitSourceControlUrlHelp'
          ui:options:
            rows: 5
          default: https://github.com/ansible/ansible-pattern-loaders
        scmBranch:
          title: Source control branch/tag/commit
          type: string
          ui:options:
            rows: 5
          default: main
          ui:help: 'Branch to checkout. In addition to branches, you can input tags, commit hashes, and arbitrary refs. Some commit hashes and refs may not be available unless you also provide a custom refspec.'
  steps:
     - id: create-project
       name: Create project
       action: rhaap:create-project
       input:
         token: ${{ parameters.token }}
         deleteIfExist: true
         values:
            projectName: 'Self Service Job Template Project'
            projectDescription: 'Self Service Job Template Project'
            organization: ${{ parameters.organization }}
            scmUrl: ${{ parameters.scmUrl }}
            scmBranch: ${{ parameters.scmBranch }}
            scmUpdateOnLaunch: true
            credentials: ${{ parameters.credentials }}
  output:
    text:
      - title: 'Project created'
        content: |
          **Info:** `${{ steps['create-project'].output.data }}`
